### ISSUE TITLE
Support patching when image container is in a deeper node 

### ISSUE THREAD

**Issue by adusumillipraveen** [squaremo/kubeyaml#20]
I am trying to use `kubeyaml` with kustomize manifest generation in flux. It works great in most of my scenarios except for  the cases when the image node is deep in `values` . It seems to be looking for image key in dicts [one level inside values ](https://github.com/squaremo/kubeyaml/blob/master/kubeyaml.py#L234)

```
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: draft-store-service
  namespace: rpe
spec:
  values:
    java:
      image: hmctspublic.azurecr.io/draft-store/service:prod-167db162 (works)
      functionaltests:
        image: hmctspublic.azurecr.io/draft-store/service-test:prod-167db162 (doesn't work) 
``` 

It would be great to support deeper paths ( flux support this and updates images in deep nodes when using `patchUpdated` configuration, but we cannot use it for other reasons) . Are there any alternatives to achieve this ? Happy to contribute with your guidance if it makes sense to be added here.
