### ISSUE TITLE
Kubeyaml returns questionable output on multidoc input including empty docs

### ISSUE THREAD

**Issue by 2opremio** [squaremo/kubeyaml#4]
This comes from https://github.com/weaveworks/flux/issues/1925

Input:

```yaml
---
# Source: webapp/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: name
  namespace: namespace
spec:
  selector:
    matchLabels:
      name: name
  template:
    metadata:
      labels:
        name: name
    spec:
      containers:
      - name: container
        image: stefanprodan/podinfo:1.4.4
---
# Source: webapp/templates/configmap.yaml
---
---
# Foo
---
---
---
---
```

The command:
```
kubeyaml.py image --namespace namespace --container container --kind deployment --name name --image bar
```

Results in:

```yaml
---
# Source: webapp/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: name
  namespace: namespace
spec:
  selector:
    matchLabels:
      name: name
  template:
    metadata:
      labels:
        name: name
    spec:
      containers:
      - name: container
        image: stefanprodan/podinfo:latest
---
...
---
...
---
...
---
...
---
...
---
...
---
...
```

The output is questionable for a few reasons:
1.  The end-of-document markers (`...`) were not present in the original document (which makes both flux and `kubectl` choke). Here is the error from `kubectl` when trying to apply the output document:
    ```
    $ pbpaste | kubectl apply -f -
    deployment.apps/name configured
    error: error parsing STDIN: error converting YAML to JSON: yaml: did not find expected node content
    ```
2. The output is missing comments.

The output seems to be correct YAML [according to the standard](https://yaml.org/spec/1.2/spec.html#id2801681) though:
> The stream format is intentionally “sloppy” to better support common use cases, such as stream concatenation.
